language: ruby
rvm:
  - "1.9.3"
install:
  - sudo echo "deb http://download.virtualbox.org/virtualbox/debian precise contrib" | sudo tee -a /etc/apt/sources.list
  - wget http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc -O- | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get -y install linux-headers-generic
  - sudo apt-get -y install virtualbox-4.2
  - VBoxManage -v
  - wget https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.2_x86_64.deb
  - sudo dpkg -i vagrant_1.7.2_x86_64.deb
script:
  - /opt/vagrant/bin/vagrant up
  - ls
  - /opt/vagrant/bin/vagrant ssh
  - cd /vagrant
  - ls
