---

- hosts: all
  sudo: yes

  pre_tasks:
    - name: add Google public key to apt
      apt_key:
        url: https://dl-ssl.google.com/linux/linux_signing_key.pub
        state: present

    - name: add Google to apt-get repositories
      apt_repository:
        repo: 'deb http://dl.google.com/linux/chrome/deb/ stable main'
        state: present

    - apt: "name={{ item }} state=installed update_cache=yes"
      with_items:
        - dbus-x11
        - default-jre
        - firefox
        - git
        - google-chrome-stable
        - libnotify4
        - nodejs
        - npm
        - python
        - xvfb

  tasks:
    - name: create /usr/lib/selenium
      file:
        dest: /usr/lib/selenium
        state: directory

    - name: download selenium-server-standalone jar
      get_url:
        url: http://selenium-release.storage.googleapis.com/2.44/selenium-server-standalone-2.44.0.jar
        dest: /usr/lib/selenium

    - name: download nw chromedriver
      get_url:
        url: http://dl.nwjs.io/v0.13.0/alpha0/chromedriver-nw-v0.13.0-alpha0-linux-x64.tar.gz
        dest: /tmp/chromedriver-nw-v0.13.0-alpha0-linux-x64.tar.gz

    - name: unarchive nw chromedriver
      unarchive:
        src: /tmp/chromedriver-nw-v0.13.0-alpha0-linux-x64.tar.gz
        dest: /tmp
        copy: no

    - name: move chromedriver executable to /usr/local/bin/
      shell: mv /tmp/chromedriver-nw-v0.13.0-alpha0-linux-x64/chromedriver /usr/local/bin/chromedriver

    - name: symlink /usr/lib/selenium/selenium-server-standalone-2.44.0.jar to /usr/lib/selenium/selenium-server-standalone.jar
      file:
        src: /usr/lib/selenium/selenium-server-standalone-2.44.0.jar
        dest: /usr/lib/selenium/selenium-server-standalone.jar
        state: link

    - name: symlink /usr/bin/nodejs to /usr/bin/node
      file:
        src: /usr/bin/nodejs
        dest: /usr/bin/node
        state: link

    - name: install bower
      command: npm install -g bower

    - name: install gulp
      command: npm install -g gulp

    - name: install web-component-tester
      command: npm install -g web-component-tester

    - name: copy xvfb init script to /etc/init.d
      template:
        src: "{{ playbook_dir }}/templates/xvfb"
        dest: /etc/init.d/xvfb
        mode: 0770

    - name: Start xvfb service
      service:
        name: xvfb
        state: started

    - name: set DISPLAY=:0
      lineinfile:
        dest: /etc/environment
        line: DISPLAY=:0

    # TODO: this could maybe be achieved via the `Xvfb -ac` option to disable access restrictions
    - name: allow localhost to connect to and display on the X server
      shell: DISPLAY=:0 xhost +localhost
